### ISSUE TITLE
Multiple projects - multiple traad servers?

### ISSUE THREAD

**Issue by rmuslimov** [abingham/traad#81]
First of all, thanks for implementing this nice and modern integration for rope library. I've thinking start doing something similar, but when I found `traad` - I'm happy :)

Can you please suggest how traad should work in my case: 
I have few projects (standard-alone app and libraries) in python that I'm always switching between, usually within a same task I can made a commits to few repositories. How can I manage multiple traad-servers on my laptop? 
I'm asking if this already known case and you have a good strategy how to solve that.
In other case, I think I can just wrap `traad-open` to determine the port by project location and manage servers by moving the to emacs-prodigy for example.

What do you think?

**Comment by abingham** [comment]
I don't have a great solution to that right now. Any ideas you've got would be great, and I'm happy to take patches.

**Comment by abingham** [comment]
Another option to consider is multi-project refactoring. Rope has support for doing refactoring across multiple projects at once, and traad has the beginnings of support for allowing that. So instead of starting and stopping traad servers, you could use a single server with multiple projects. Perhaps this fits your needs.

Support for this feature is pretty slim right now, though. In fact, it looks like the emacs client doesn't support it at all (there's some commented-out code related to it). But it should in principle work just fine; I know I experimented with a bit outside of traad.

**Comment by abingham** [comment]
Something else to consider it modifying the server so that it can support multiple, independent projects at once. We'd need to think about how it matched requests with projects, but we could look at projects like ycmd for inspiration and guidance.

**Comment by abingham** [comment]
@rmuslimov I've been doing some work on using multiple servers. If you update to the latest traad and the latest traad-emacs, it should do what you want. The basic idea is that we try to detect the "project root" for the file you're working on (i.e. the dominant directory containing a ".ropeproject"). If there's no server running for that directory we start one, otherwise we just the existing one.

It all seems to work reasonably well for me, but I'd love any feedback from another user.
